name: BxSerialSender
version: '${version}'
main: lord225.bxserialsender.BxUDPSender
api-version: 1.18
authors: [ Lord225, BrzechiX ]
commands:
  updsend:
    description: Send data over a UDP socket. The first argument, <address>, specifies the address to send the data to. The second argument, <port>, specifies the port number to send the data on. The remaining arguments represent the data to be sent.
  udpopen:
    description: Open a UDP socket for communication. The first argument, <address>, specifies the address to bind the socket to. The second argument, <port>, specifies the port number to bind the socket to.
  udpclose:
    description: Close a previously opened UDP socket. The argument, <address>, specifies the address of the socket to close.
  udpaddcallback:
    description: Add a callback to a previously opened UDP socket. The first argument, <address>, specifies the address of the socket to add the callback to. The second argument, <byte>, is the byte that triggers the callback. The remaining arguments, <command>, represent the command to execute when the callback is triggered.
  udpclearcallbacks:
    description: Clear all callbacks from a previously opened UDP socket. The argument, <address>, specifies the address of the socket to clear the callbacks from.
